# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: >-
          docker run
          -d
          --name mysql 
          -p 3306:3306 
          -e MYSQL_RANDOM_ROOT_PASSWORD=true 
          -e MYSQL_DATABASE=laravel
          -e MYSQL_USER=laravel 
          -e MYSQL_PASSWORD=Password01! 
          mysql
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
                  
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mcasperson/laravelapp
          build-args: db_host=172.17.0.1,db_username=laravel,db_database=laravel,db_password=Password01!
